---
name: First Deployment Check
description: Check to see if this is the first deployment
inputs:
  managementGroupId:
    description: 'The management group id to check'
    required: true

runs:
  using: "composite"
  steps:
    - name: First Deployment Check
      id: firstDeployment
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          $ErrorActionPreference = "Stop"

          $mgId = $env:MG_TO_CHECK
          $firstDeployment = $true

          try {
            $managementGroup = Get-AzManagementGroup -GroupName $mgId -Expand -ErrorAction Stop
            Write-Host "Found the '$mgId' Management Group."

            $children = @($managementGroup.Children | Where-Object { $_.Type -eq "Microsoft.Management/managementGroups" })

            if ($children.Count -gt 0) {
              Write-Host "The '$mgId' Management Group has child management groups -> NOT first deployment."
              $firstDeployment = $false
            } else {
              Write-Host "The '$mgId' Management Group has NO child management groups -> assuming first deployment."
              $firstDeployment = $true
            }
          }
          catch {
            $msg = $_.Exception.Message
            Write-Warning "Could not read management group '$mgId'. Assuming first deployment. Error: $msg"
            $firstDeployment = $true
          }

          echo "firstDeployment=$firstDeployment" >> $env:GITHUB_ENV
          echo "firstDeployment=$firstDeployment" >> $env:GITHUB_OUTPUT
      env:
        MG_TO_CHECK: ${{ inputs.managementGroupId }}

