---
name: First Deployment Check
description: Check to see if this is the first deployment
inputs:
  managementGroupId:
    description: 'The management group id to check'
    required: true

runs:
  using: "composite"
  steps:
    - name: First Deployment Check
      id: firstDeployment
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          $ErrorActionPreference = "Stop"
        
          $mgId = $env:MG_TO_CHECK
          $firstDeployment = $true
        
          try {
            # If we can retrieve the MG, then the "intermediate root" exists -> not first deployment.
            $null = Get-AzManagementGroup -GroupName $mgId -ErrorAction Stop
            Write-Host "Found the '$mgId' Management Group -> NOT first deployment."
            $firstDeployment = $false
          }
          catch {
            $msg = $_.Exception.Message
          
            $isNotFound = ($msg -match '(?i)not\s*found|could\s*not\s*be\s*found|ResourceNotFound|404')
            $isAuthOrScope = ($msg -match '(?i)does not have authorization|AuthorizationFailed|Forbidden|403|scope is invalid')
          
            if ($isNotFound) {
              Write-Warning "Management group '$mgId' not found. Treating as first deployment. Error: $msg"
              $firstDeployment = $true
            }
            elseif ($isAuthOrScope) {
              Write-Error "Cannot read management group '$mgId' due to missing permissions. This is NOT a valid first-deployment signal. Error: $msg"
              throw
            }
            else {
              Write-Error "Unexpected error reading management group '$mgId'. Error: $msg"
              throw
            }
          }
        
          echo "firstDeployment=$firstDeployment" >> $env:GITHUB_ENV
          echo "firstDeployment=$firstDeployment" >> $env:GITHUB_OUTPUT

      env:
        MG_TO_CHECK: ${{ inputs.managementGroupId }}

