---
name: First Deployment Check
description: Check to see if this is the first deployment
inputs:
  managementGroupId:
    description: 'The management group id to check'
    required: true

runs:
  using: "composite"
  steps:
    - name: First Deployment Check
      id: firstDeployment
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          $ErrorActionPreference = "Stop"
        
          $mgId = $env:MG_TO_CHECK
          $firstDeployment = $true
        
          try {
            # If we can retrieve the MG, then the "intermediate root" exists -> not first deployment.
            $null = Get-AzManagementGroup -GroupName $mgId -ErrorAction Stop
            Write-Host "Found the '$mgId' Management Group -> NOT first deployment."
            $firstDeployment = $false
          }
          catch {
            $msg = $_.Exception.Message
            Write-Warning "Could not read management group '$mgId'. Assuming first deployment. Error: $msg"
            $firstDeployment = $true
          }
        
          echo "firstDeployment=$firstDeployment" >> $env:GITHUB_ENV
          echo "firstDeployment=$firstDeployment" >> $env:GITHUB_OUTPUT

      env:
        MG_TO_CHECK: ${{ inputs.managementGroupId }}

